server:
  applicationConnectors:
    - type: http
      port: 9056
  adminConnectors:
    - type: http
      port: 9057

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5433/household?user=postgres&password=mysecretpassword

jwtSecret: "mySecret"